=begin
#lthn API

#Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LthnApi::RunnerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RunnerApi' do
  before do
    # run before each test
    @api_instance = LthnApi::RunnerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RunnerApi' do
    it 'should create an instance of RunnerApi' do
      expect(@api_instance).to be_instance_of(LthnApi::RunnerApi)
    end
  end

  # unit tests for get_v1_runner_models
  # List configured runner model routes
  # 
  # @param [Hash] opts the optional parameters
  # @return [GetV1RunnerModels200Response]
  describe 'get_v1_runner_models test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_v1_runner_chat
  # Multi-turn chat completion
  # 
  # @param post_v1_runner_chat_request 
  # @param [Hash] opts the optional parameters
  # @return [PostV1RunnerChat200Response]
  describe 'post_v1_runner_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_v1_runner_generate
  # Single-prompt generation
  # 
  # @param post_v1_runner_generate_request 
  # @param [Hash] opts the optional parameters
  # @return [PostV1RunnerChat200Response]
  describe 'post_v1_runner_generate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
