=begin
#lthn API

#Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LthnApi::PostV1RunnerChat200ResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LthnApi::PostV1RunnerChat200ResponseData do
  #let(:instance) { LthnApi::PostV1RunnerChat200ResponseData.new }

  describe 'test an instance of PostV1RunnerChat200ResponseData' do
    it 'should create an instance of PostV1RunnerChat200ResponseData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LthnApi::PostV1RunnerChat200ResponseData)
    end
  end

  describe 'test attribute "reply"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
