=begin
#lthn API

#Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'lthn_api/api_client'
require 'lthn_api/api_error'
require 'lthn_api/api_model_base'
require 'lthn_api/version'
require 'lthn_api/configuration'

# Models
require 'lthn_api/models/error'
require 'lthn_api/models/get_health200_response'
require 'lthn_api/models/get_health429_response'
require 'lthn_api/models/get_v1_runner_models200_response'
require 'lthn_api/models/get_v1_runner_models200_response_data'
require 'lthn_api/models/meta'
require 'lthn_api/models/post_v1_runner_chat200_response'
require 'lthn_api/models/post_v1_runner_chat200_response_data'
require 'lthn_api/models/post_v1_runner_chat_request'
require 'lthn_api/models/post_v1_runner_chat_request_messages_inner'
require 'lthn_api/models/post_v1_runner_generate_request'
require 'lthn_api/models/response'

# APIs
require 'lthn_api/api/runner_api'
require 'lthn_api/api/system_api'

module LthnApi
  class << self
    # Customize default settings for the SDK using block.
    #   LthnApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
